### ISSUE TITLE
WiFi Support

### ISSUE THREAD

**Issue by NicoStaehle** [hideakitai/HyperDeck#1]
Hey!

I can`t get it to work. The Hyperdeck has a static Ip. I can control the hyperdeck via Terminal from a Mac.
The Arduino also has a connection to the same network.

But for some reason I get a "connecting to 192.168.98.69... FAILED".

Heres my code for the ESP32:

#include "WiFi.h"
#include <HyperDeck.h>
 
const char* ssid = "12345678";
const char* password = "12345678";

// Set your Static IP address
IPAddress local_IP(192, 168, 98, 100);
IPAddress gateway(192, 168, 98, 1);
IPAddress subnet(255, 255, 255, 0);

// HyperDeck IP
const IPAddress hyperdeck_ip{192, 168, 98, 69};
HyperDeck::Controller deck;

void setup() {
  Serial.begin(115200);

  // Configures static IP address
  if (!WiFi.config(local_IP, gateway, subnet)) {
    Serial.println("STA Failed to configure");
  }
  
  // Connect to Wi-Fi network with SSID and password
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  // Print local IP address and start web server
  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

delay (200);

deck.connect(hyperdeck_ip);

 Serial.print("connecting to ");
    Serial.print(hyperdeck_ip);
    Serial.print("... ");
    if (deck.connect(hyperdeck_ip)) {
        Serial.println("SUCCESS");
    } else {
        Serial.println("FAILED");
    }

}
 
void loop() {
    while (Serial.available()) {
        char c = Serial.read();
        if (c == 'p') {
            deck.play();
        } else if (c == 's') {
            deck.stop();
        } else if (c == 'n') {
            deck.goto_clip_forward(1);
        } else if (c == 'b') {
            deck.goto_clip_backward(1);
        } else if (c == 'm') {
            static HyperDeck::StopMode m {HyperDeck::StopMode::BLACK_SCREEN};
            if (m == HyperDeck::StopMode::BLACK_SCREEN)
                m = HyperDeck::StopMode::LAST_FRAME;
            else if (m == HyperDeck::StopMode::LAST_FRAME)
                m = HyperDeck::StopMode::NEXT_FRAME;
            else if (m == HyperDeck::StopMode::NEXT_FRAME)
                m = HyperDeck::StopMode::BLACK_SCREEN;
            deck.play_option(m);
        } else if (c == 'l') {
            static bool b {true};
            deck.play_loop(b);
            b = !b;
        } else if (c == 'c') {
            static bool b {true};
            deck.play_single_clip(b);
            b = !b;
        }
    }
}

Any Ideas?
Best,
Nico

**Comment by jonasfehr** [comment]
Fast Guess... You try to connect twice, use is_connected in the if statement.

**Comment by NicoStaehle** [comment]
Hey @jonasfehr!

I can connect the ESP to the network, but do not get a connection to the Hyperdeck.

**Comment by jonasfehr** [comment]
I understood, but you have the line `deck.connect(hyperdeck_ip)` twice in your code, which might be your issue?
I used the library with great success in a project of mine, without any problems.

**Comment by hideakitai** [comment]
@NicoStaehle Hi, the Wi-Fi connection itself has failed.  Please check the ping first.  Are both PC to Hyperdeck and PC to ESP successful?

@jonasfehr Thank you for your help🙌

**Comment by NicoStaehle** [comment]
Hi!

I can Ping the Hyperdeck and the ESP. Both are in the same network (192.168.98.x).
In the serialMonitor from the Arduino IDE i got this Message:

15:26:06.977 -> .
15:26:06.977 -> WiFi connected.
15:26:07.024 -> IP address: 
15:26:07.024 -> 192.168.98.100
15:26:07.177 -> connecting to 192.168.98.69... FAILED

192.168.98.69 is the Hyperdeck
192.168.98.100 is the ESP
(Both I can ping)


So, this Code should work right?

#include "WiFi.h"
#include <HyperDeck.h>
 
const char* ssid = "12345678";
const char* password = "12345678";


// Set your Static IP address
IPAddress local_IP(192, 168, 98, 100);
IPAddress gateway(192, 168, 98, 1);
IPAddress subnet(255, 255, 255, 0);


// HyperDeck IP
const IPAddress hyperdeck_ip{192, 168, 98, 69};
HyperDeck::Controller deck;


void setup() {
  Serial.begin(115200);

  // Configures static IP address
  if (!WiFi.config(local_IP, gateway, subnet)) {
    Serial.println("STA Failed to configure");
  }
  
  // Connect to Wi-Fi network with SSID and password
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  // Print local IP address and start web server
  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

delay (200);

deck.connect(hyperdeck_ip);


}
 
void loop() {
    while (Serial.available()) {
        char c = Serial.read();
        if (c == 'p') {
            deck.play();
        } else if (c == 's') {
            deck.stop();
        } else if (c == 'n') {
            deck.goto_clip_forward(1);
        } else if (c == 'b') {
            deck.goto_clip_backward(1);
        } else if (c == 'm') {
            static HyperDeck::StopMode m {HyperDeck::StopMode::BLACK_SCREEN};
            if (m == HyperDeck::StopMode::BLACK_SCREEN)
                m = HyperDeck::StopMode::LAST_FRAME;
            else if (m == HyperDeck::StopMode::LAST_FRAME)
                m = HyperDeck::StopMode::NEXT_FRAME;
            else if (m == HyperDeck::StopMode::NEXT_FRAME)
                m = HyperDeck::StopMode::BLACK_SCREEN;
            deck.play_option(m);
        } else if (c == 'l') {
            static bool b {true};
            deck.play_loop(b);
            b = !b;
        } else if (c == 'c') {
            static bool b {true};
            deck.play_single_clip(b);
            b = !b;
        }
    }
}

**Comment by hideakitai** [comment]
@NicoStaehle Ah, do you want to connect HyperDeck via WiFi? Currently only Ethernet is supported. I think I can support WiFi if you want.

**Comment by NicoStaehle** [comment]
Yes exact!
I try to build a wireless control for the Hyperdeck!
If you have an option for ESP32 / Wireless that would be perfect!!!!!

**Comment by hideakitai** [comment]
@NicoStaehle Supported. I think v0.2.0 works with WiFi. Can you try it?

**Comment by NicoStaehle** [comment]
@hideakitai Hey! Works fine! Perfect! Thanks alot!
