### ISSUE TITLE
Arduino stalls on network loss

### ISSUE THREAD

**Issue by Plux-in-spaaace** [hideakitai/HyperDeck#2]
Hi there, first of all many thanks for this script. 
It works beautifully to keep our hyperdecks running in some of our installations.

Sadly we do face some issues that i suspect relate to the ethernet shield or the way the script is handling the ethernet hardware. When powered on together with the hyperdeck, the script will run as intended and it will keep pressing play on our Hyperdecks. But once the ethernet cable gets disconnected, or when any of the network equipment the Arduino and Hyperdeck are connected to are slow to come to life, the arduino will not send any more commands. 

I am not an experienced arduino user or programmer, and i have tried to edit the script to include restarting the ethernet shield in the void loop(), but the arduino will still stall once the ethernet cable becomes disconnected. After reconnecting the ethernet connection to the arduino it will continue to not do anything, until a full powercycle of the arduino.  

Are there any good tips i can use to make this script a bit more bulletproof in case of cable disconnects and/or network device or power failures? My main goal is for it to keep activating the hyperdecks no matter what the situation. So any installation using this script would be fixable with a mere powercycle at worst. Many thanks in advance from a very thankful user.

**Comment by hideakitai** [comment]
Hi, if rebooting/resetting Arduino won't address the connection issue, it is caused by the hardware. So physical power cycle is the only way to recover from this issue... I'm sorry I can't be of much help. I hope this gets resolved.
